# -*- coding: utf-8 -*-
"""
---------------------------------------
@file    : mail_templet
@Version : ??
@Author  : Andy Zang
@software: PyCharm
@For     : Auto_Mail
---------------------------------------
"""

# History:
# 2022/1/25: Create

head = """
Dear {receiver}
"""

body = """
good morning!
"""

sign = """
Best wishes
Andy
"""

acknowlege = """
This email contains content generated by a script, I apologize for any errors in advance.
"""

if __name__ == '__main__':
    print(head.format(receiver="andy")+body+sign+acknowlege)
